USE QLSVNhom;
GO

-- 1. SP_INS_PUBLIC_ENCRYPT_NHANVIEN: Thêm nhân viên mới (Mã hóa và băm được thực hiện ở Client)
CREATE OR ALTER PROCEDURE SP_INS_PUBLIC_ENCRYPT_NHANVIEN
    @MANV VARCHAR(20),
    @HOTEN NVARCHAR(100),
    @EMAIL VARCHAR(20),
    @LUONG VARBINARY(MAX),
    @TENDN NVARCHAR(100),
    @MK VARBINARY(MAX),
    @PUB VARCHAR(MAX)
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRANSACTION;
    BEGIN TRY
        -- Kiểm tra trùng mã nhân viên
        IF EXISTS (SELECT 1 FROM NHANVIEN WHERE MANV = @MANV)
            THROW 50001, N'Mã nhân viên đã tồn tại.', 1;

        -- Kiểm tra trùng tên đăng nhập
        IF EXISTS (SELECT 1 FROM NHANVIEN WHERE TENDN = @TENDN)
            THROW 50002, N'Tên đăng nhập đã tồn tại.', 1;

        -- Lưu trực tiếp dữ liệu đã mã hóa và băm từ client
        INSERT INTO NHANVIEN (MANV, HOTEN, EMAIL, LUONG, TENDN, MATKHAU, PUBKEY)
        VALUES (@MANV, @HOTEN, @EMAIL, @LUONG, @TENDN, @MK, @PUB);

        COMMIT TRANSACTION;
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0 ROLLBACK;
        DECLARE @ErrMsg NVARCHAR(4000) = ERROR_MESSAGE();
        RAISERROR(@ErrMsg, 16, 1);
    END CATCH
END
GO

-- 2. SP_SEL_PUBLIC_ENCRYPT_NHANVIEN: Lấy thông tin nhân viên kèm lương đã mã hóa
CREATE OR ALTER PROCEDURE SP_SEL_PUBLIC_ENCRYPT_NHANVIEN
    @TENDN NVARCHAR(100),
    @MK VARBINARY(MAX)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT
        n.MANV,
        n.HOTEN,
        n.EMAIL,
        n.LUONG,
        n.PUBKEY,
        n.TENDN
    FROM NHANVIEN n
    WHERE n.TENDN = @TENDN COLLATE SQL_Latin1_General_CP1_CS_AS
      AND n.MATKHAU = @MK;
END
GO

-- 3. SP_LOGIN_NHANVIEN: Xác thực đăng nhập (Gộp thành 1 SP duy nhất chống MANV Enumeration)
CREATE OR ALTER PROCEDURE SP_LOGIN_NHANVIEN
    @LOGIN VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (SELECT 1 FROM NHANVIEN WHERE MANV = @LOGIN)
    BEGIN
        SELECT MANV, HOTEN, EMAIL, TENDN, PUBKEY, MATKHAU
        FROM NHANVIEN
        WHERE MANV = @LOGIN;
    END
    ELSE
    BEGIN
        -- Trả về dữ liệu dummy có cấu trúc y hệt để tránh kẻ tấn công dò tìm tài khoản
        SELECT 
            @LOGIN AS MANV, 
            N'Không tồn tại' AS HOTEN, 
            'dummy@fit.hcmus.vn' AS EMAIL, 
            'dummy' AS TENDN, 
            '' AS PUBKEY, 
            0x1234567890ABCDEF1234567890ABCDEF12345678 AS MATKHAU;
    END
END
GO

-- 4. SP_CHANGE_PASSWORD_NHANVIEN: Đổi mật khẩu nhân viên và re-encrypt LUONG
CREATE OR ALTER PROCEDURE SP_CHANGE_PASSWORD_NHANVIEN
    @MANV VARCHAR(20),
    @OLD_MK VARBINARY(MAX),
    @NEW_MK VARBINARY(MAX),
    @NEW_PUB VARCHAR(MAX),
    @NEW_LUONG VARBINARY(MAX) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    -- Xác thực lại mật khẩu cũ trước khi cho phép đổi
    IF NOT EXISTS (SELECT 1 FROM NHANVIEN WHERE MANV = @MANV AND MATKHAU = @OLD_MK)
        THROW 50015, N'Mật khẩu cũ không chính xác.', 1;

    UPDATE NHANVIEN
    SET MATKHAU = @NEW_MK,
        PUBKEY = @NEW_PUB,
        LUONG = @NEW_LUONG
    WHERE MANV = @MANV;
END
GO

-- 5. SP_SEL_LOP: Lấy tất cả lớp học trong hệ thống
CREATE OR ALTER PROCEDURE SP_SEL_LOP AS
BEGIN
    SET NOCOUNT ON;
    SELECT MALOP, TENLOP, MANV
    FROM LOP
    ORDER BY MALOP;
END
GO

-- 6. SP_SEL_LOP_BY_OWNER: Lấy danh sách lớp do nhân viên quản lý
CREATE OR ALTER PROCEDURE SP_SEL_LOP_BY_OWNER
    @CALLER_MANV VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT MALOP, TENLOP, MANV
    FROM LOP
    WHERE MANV = @CALLER_MANV
    ORDER BY MALOP;
END
GO

-- 7. SP_INS_LOP: Thêm lớp học mới
CREATE OR ALTER PROCEDURE SP_INS_LOP
    @CALLER_MANV VARCHAR(20),
    @MALOP VARCHAR(20),
    @TENLOP NVARCHAR(100),
    @MANV VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    -- Ràng buộc: Chỉ được tạo lớp cho chính mình phụ trách
    IF @MANV <> @CALLER_MANV
        THROW 50003, N'Chỉ được tạo lớp do chính mình phụ trách.', 1;

    INSERT INTO LOP (MALOP, TENLOP, MANV)
    VALUES (@MALOP, @TENLOP, @MANV);
END
GO

-- 8. SP_UPD_LOP: Cập nhật lớp học có kiểm tra quyền sở hữu
CREATE OR ALTER PROCEDURE SP_UPD_LOP
    @CALLER_MANV VARCHAR(20),
    @MALOP VARCHAR(20),
    @TENLOP NVARCHAR(100),
    @NEW_MANV VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    -- Ràng buộc: Chỉ người đang quản lý lớp này mới được phép cập nhật lớp
    IF NOT EXISTS (SELECT 1 FROM LOP WHERE MALOP = @MALOP AND MANV = @CALLER_MANV)
        THROW 50005, N'Bạn không có quyền cập nhật lớp này.', 1;

    UPDATE LOP
    SET TENLOP = @TENLOP, MANV = @NEW_MANV
    WHERE MALOP = @MALOP;
END
GO

-- 9. SP_DEL_LOP: Xóa lớp học (Kiểm tra điều kiện ràng buộc)
CREATE OR ALTER PROCEDURE SP_DEL_LOP
    @CALLER_MANV VARCHAR(20),
    @MALOP VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    IF NOT EXISTS (SELECT 1 FROM LOP WHERE MALOP = @MALOP AND MANV = @CALLER_MANV)
        THROW 50005, N'Không có quyền xóa lớp này.', 1;

    IF EXISTS (SELECT 1 FROM SINHVIEN WHERE MALOP = @MALOP)
        THROW 50006, N'Lớp vẫn còn sinh viên, không thể xóa.', 1;

    DELETE FROM LOP WHERE MALOP = @MALOP;
END
GO

-- 10. SP_SEL_SINHVIEN_BY_OWNER: Lấy sinh viên thuộc các lớp do nhân viên quản lý
CREATE OR ALTER PROCEDURE SP_SEL_SINHVIEN_BY_OWNER
    @CALLER_MANV VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT s.MASV, s.HOTEN, s.NGAYSINH, s.DIACHI, s.MALOP, s.TENDN
    FROM SINHVIEN s
    INNER JOIN LOP l ON l.MALOP = s.MALOP
    WHERE l.MANV = @CALLER_MANV
    ORDER BY s.MALOP, s.MASV;
END
GO

-- 11. SP_SEL_SINHVIEN_BY_CLASS: Lấy sinh viên của một lớp (Tất cả nhân viên đều xem được)
CREATE OR ALTER PROCEDURE SP_SEL_SINHVIEN_BY_CLASS
    @CALLER_MANV VARCHAR(20) = NULL,
    @MALOP VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT MASV, HOTEN, NGAYSINH, DIACHI, MALOP, TENDN
    FROM SINHVIEN
    WHERE MALOP = @MALOP
    ORDER BY MASV;
END
GO

-- 12. SP_INS_SINHVIEN: Thêm sinh viên mới (Hash mật khẩu SHA1 được thực hiện ở Client)
CREATE OR ALTER PROCEDURE SP_INS_SINHVIEN
    @CALLER_MANV VARCHAR(20),
    @MASV VARCHAR(20),
    @HOTEN NVARCHAR(100),
    @NGAYSINH DATETIME,
    @DIACHI NVARCHAR(200),
    @MALOP VARCHAR(20),
    @TENDN NVARCHAR(100),
    @MK VARBINARY(MAX)
AS
BEGIN
    SET NOCOUNT ON;
    -- Kiểm tra quyền quản lý lớp trước khi thêm sinh viên
    IF NOT EXISTS (SELECT 1 FROM LOP WHERE MALOP = @MALOP AND MANV = @CALLER_MANV)
        THROW 50008, N'Không có quyền thêm sinh viên vào lớp này.', 1;

    INSERT INTO SINHVIEN (MASV, HOTEN, NGAYSINH, DIACHI, MALOP, TENDN, MATKHAU)
    VALUES (@MASV, @HOTEN, @NGAYSINH, @DIACHI, @MALOP, @TENDN, @MK);
END
GO

-- 13. SP_UPD_SINHVIEN: Cập nhật thông tin sinh viên có phân quyền sở hữu
CREATE OR ALTER PROCEDURE SP_UPD_SINHVIEN
    @CALLER_MANV VARCHAR(20),
    @MASV VARCHAR(20),
    @HOTEN NVARCHAR(100),
    @NGAYSINH DATETIME,
    @DIACHI NVARCHAR(200),
    @TENDN NVARCHAR(100),
    @MK VARBINARY(MAX) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    -- Ràng buộc: Giáo viên phải quản lý lớp của sinh viên này mới được phép cập nhật
    IF NOT EXISTS (
        SELECT 1 FROM SINHVIEN s
        INNER JOIN LOP l ON l.MALOP = s.MALOP
        WHERE s.MASV = @MASV AND l.MANV = @CALLER_MANV
    )
        THROW 50009, N'Bạn không có quyền cập nhật thông tin sinh viên này.', 1;

    -- Kiểm tra trùng tên đăng nhập của sinh viên khác
    IF EXISTS (SELECT 1 FROM SINHVIEN WHERE TENDN = @TENDN AND MASV <> @MASV)
        THROW 50002, N'Tên đăng nhập đã tồn tại.', 1;

    UPDATE SINHVIEN
    SET HOTEN = @HOTEN,
        NGAYSINH = @NGAYSINH,
        DIACHI = @DIACHI,
        TENDN = @TENDN,
        MATKHAU = COALESCE(@MK, MATKHAU)
    WHERE MASV = @MASV;
END
GO

-- 14. SP_DEL_SINHVIEN_BY_OWNER: Xóa sinh viên và bảng điểm liên quan
CREATE OR ALTER PROCEDURE SP_DEL_SINHVIEN_BY_OWNER
    @CALLER_MANV VARCHAR(20),
    @MASV VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    IF NOT EXISTS (
        SELECT 1 FROM SINHVIEN s
        INNER JOIN LOP l ON l.MALOP = s.MALOP
        WHERE s.MASV = @MASV AND l.MANV = @CALLER_MANV
    )
        THROW 50011, N'Không có quyền xóa sinh viên này.', 1;

    BEGIN TRANSACTION;
    BEGIN TRY
        DELETE FROM BANGDIEM WHERE MASV = @MASV;
        DELETE FROM SINHVIEN WHERE MASV = @MASV;
        COMMIT;
    END TRY
    BEGIN CATCH
        ROLLBACK;
        THROW;
    END CATCH
END
GO

-- 15. SP_UPSERT_BANGDIEM: Cập nhật hoặc thêm mới điểm (Đã mã hóa từ Client)
CREATE OR ALTER PROCEDURE SP_UPSERT_BANGDIEM
    @CALLER_MANV VARCHAR(20),
    @MASV VARCHAR(20),
    @MAHP VARCHAR(20),
    @DIEMTHI VARBINARY(MAX)
AS
BEGIN
    SET NOCOUNT ON;
    -- Kiểm tra quyền quản lý sinh viên trước khi nhập điểm
    IF NOT EXISTS (
        SELECT 1 FROM SINHVIEN s
        INNER JOIN LOP l ON l.MALOP = s.MALOP
        WHERE s.MASV = @MASV AND l.MANV = @CALLER_MANV
    )
        THROW 50013, N'Không có quyền nhập điểm cho sinh viên này.', 1;

    IF EXISTS (SELECT 1 FROM BANGDIEM WHERE MASV = @MASV AND MAHP = @MAHP)
        UPDATE BANGDIEM SET DIEMTHI = @DIEMTHI WHERE MASV = @MASV AND MAHP = @MAHP;
    ELSE
        INSERT INTO BANGDIEM (MASV, MAHP, DIEMTHI) VALUES (@MASV, @MAHP, @DIEMTHI);
END
GO

-- 16. SP_SEL_BANGDIEM_DETAILED_BY_STUDENT: Xem bảng điểm chi tiết của sinh viên
CREATE OR ALTER PROCEDURE SP_SEL_BANGDIEM_DETAILED_BY_STUDENT
    @CALLER_MANV VARCHAR(20),
    @MASV VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT b.MASV, b.MAHP, h.TENHP, h.SOTC, b.DIEMTHI
    FROM BANGDIEM b
    INNER JOIN HOCPHAN h ON h.MAHP = b.MAHP
    INNER JOIN SINHVIEN s ON s.MASV = b.MASV
    INNER JOIN LOP l ON l.MALOP = s.MALOP
    WHERE l.MANV = @CALLER_MANV AND b.MASV = @MASV
    ORDER BY b.MAHP;
END
GO

-- 17. SP_SEL_BANGDIEM_BY_OWNER: Lấy toàn bộ điểm thi do giáo viên này quản lý (Phục vụ re-encrypt)
CREATE OR ALTER PROCEDURE SP_SEL_BANGDIEM_BY_OWNER
    @CALLER_MANV VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT b.MASV, b.MAHP, b.DIEMTHI
    FROM BANGDIEM b
    INNER JOIN SINHVIEN s ON s.MASV = b.MASV
    INNER JOIN LOP l ON l.MALOP = s.MALOP
    WHERE l.MANV = @CALLER_MANV;
END
GO

-- 18. SP_UPD_BANGDIEM_RE_ENCRYPT: Cập nhật lại điểm sau khi re-encrypt có kiểm tra quyền sở hữu
CREATE OR ALTER PROCEDURE SP_UPD_BANGDIEM_RE_ENCRYPT
    @CALLER_MANV VARCHAR(20),
    @MASV VARCHAR(20),
    @MAHP VARCHAR(20),
    @DIEMTHI VARBINARY(MAX)
AS
BEGIN
    SET NOCOUNT ON;
    -- Ràng buộc: Giáo viên phải quản lý sinh viên đó mới được cập nhật điểm
    IF NOT EXISTS (
        SELECT 1 FROM SINHVIEN s
        INNER JOIN LOP l ON l.MALOP = s.MALOP
        WHERE s.MASV = @MASV AND l.MANV = @CALLER_MANV
    )
        THROW 50013, N'Không có quyền cập nhật điểm cho sinh viên này.', 1;

    UPDATE BANGDIEM
    SET DIEMTHI = @DIEMTHI
    WHERE MASV = @MASV AND MAHP = @MAHP;
END
GO

-- 19. SP_SEL_DASHBOARD_SUMMARY: Tổng hợp dữ liệu cho Dashboard
CREATE OR ALTER PROCEDURE SP_SEL_DASHBOARD_SUMMARY
    @CALLER_MANV VARCHAR(20)
AS
BEGIN
    SET NOCOUNT ON;
    SELECT 
        (SELECT COUNT(*) FROM LOP WHERE MANV = @CALLER_MANV) AS TotalClasses,
        (SELECT COUNT(*) FROM SINHVIEN s JOIN LOP l ON s.MALOP = l.MALOP WHERE l.MANV = @CALLER_MANV) AS TotalStudents,
        (SELECT COUNT(*) FROM HOCPHAN) AS TotalCourses,
        (SELECT COUNT(*) FROM BANGDIEM b JOIN SINHVIEN s ON b.MASV = s.MASV JOIN LOP l ON s.MALOP = l.MALOP WHERE l.MANV = @CALLER_MANV) AS EnteredGrades;
END
GO

-- 20. SP_SEL_HOCPHAN: Tải danh mục học phần
CREATE OR ALTER PROCEDURE SP_SEL_HOCPHAN AS
BEGIN
    SET NOCOUNT ON;
    SELECT MAHP, TENHP, SOTC FROM HOCPHAN ORDER BY MAHP;
END
GO

-- 21. SP_SEL_ALL_NHANVIEN: Lấy danh sách toàn bộ nhân viên (Thông tin công khai)
CREATE OR ALTER PROCEDURE SP_SEL_ALL_NHANVIEN AS
BEGIN
    SET NOCOUNT ON;
    SELECT MANV, HOTEN, EMAIL, TENDN
    FROM NHANVIEN
    ORDER BY MANV;
END
GO